import { describe, it, expect, beforeEach, afterEach, vi } from "vitest";
import fs from "fs";
import path from "path";
import os from "os";

// Mock the global objects that GitHub Actions provides
const mockCore = {
  debug: vi.fn(),
  info: vi.fn(),
  warning: vi.fn(),
  error: vi.fn(),
  setFailed: vi.fn(),
  setOutput: vi.fn(),
  summary: {
    addRaw: vi.fn().mockReturnThis(),
    write: vi.fn().mockResolvedValue(),
  },
};

const mockContext = {
  runId: 12345,
  repo: {
    owner: "testowner",
    repo: "testrepo",
  },
  payload: {
    repository: {
      html_url: "https://github.com/testowner/testrepo",
    },
  },
};

// Set up global mocks before importing the module
global.core = mockCore;
global.context = mockContext;

describe("generate_footer.cjs", () => {
  let generateFooter;
  let generateXMLMarker;
  let testPromptsDir;
  let originalEnv;

  beforeEach(async () => {
    // Save original environment
    originalEnv = process.env.GH_AW_PROMPTS_DIR;

    // Set up test prompts directory
    testPromptsDir = path.join(os.tmpdir(), "gh-aw-test-footer", "prompts");
    if (!fs.existsSync(testPromptsDir)) {
      fs.mkdirSync(testPromptsDir, { recursive: true });
    }

    // Create the workflow install note template
    const templatePath = path.join(testPromptsDir, "workflow_install_note.md");
    const templateContent = "To add this workflow in your repository, run `gh aw add {workflow_source}`. See [usage guide](https://githubnext.github.io/gh-aw/guides/packaging-imports/).";
    fs.writeFileSync(templatePath, templateContent, "utf8");

    // Set environment to use test directory
    process.env.GH_AW_PROMPTS_DIR = testPromptsDir;

    // Reset mocks
    vi.clearAllMocks();
    // Clear env vars
    delete process.env.GH_AW_ENGINE_ID;
    delete process.env.GH_AW_ENGINE_VERSION;
    delete process.env.GH_AW_ENGINE_MODEL;
    delete process.env.GH_AW_TRACKER_ID;

    // Dynamic import to get fresh module state
    const module = await import("./generate_footer.cjs");
    generateFooter = module.generateFooter;
    generateXMLMarker = module.generateXMLMarker;
  });

  afterEach(() => {
    // Restore original environment
    if (originalEnv !== undefined) {
      process.env.GH_AW_PROMPTS_DIR = originalEnv;
    } else {
      delete process.env.GH_AW_PROMPTS_DIR;
    }

    // Clean up test directory
    if (testPromptsDir && fs.existsSync(testPromptsDir)) {
      fs.rmSync(testPromptsDir, { recursive: true, force: true });
    }
  });

  describe("generateFooter", () => {
    it("should generate basic footer with workflow name and run URL", () => {
      const result = generateFooter("Test Workflow", "https://github.com/test/repo/actions/runs/123", "", "", undefined, undefined, undefined);

      expect(result).toContain("> AI generated by [Test Workflow](https://github.com/test/repo/actions/runs/123)");
      expect(result).not.toContain("for #");
      expect(result).not.toContain("gh aw add");
    });

    it("should include issue number reference when provided", () => {
      const result = generateFooter("Test Workflow", "https://github.com/test/repo/actions/runs/123", "", "", 42, undefined, undefined);

      expect(result).toContain("> AI generated by [Test Workflow](https://github.com/test/repo/actions/runs/123) for #42");
    });

    it("should include PR number reference when provided", () => {
      const result = generateFooter("Test Workflow", "https://github.com/test/repo/actions/runs/123", "", "", undefined, 99, undefined);

      expect(result).toContain("> AI generated by [Test Workflow](https://github.com/test/repo/actions/runs/123) for #99");
    });

    it("should include discussion number reference when provided", () => {
      const result = generateFooter("Test Workflow", "https://github.com/test/repo/actions/runs/123", "", "", undefined, undefined, 7);

      expect(result).toContain("> AI generated by [Test Workflow](https://github.com/test/repo/actions/runs/123) for discussion #7");
    });

    it("should prioritize issue number over PR number", () => {
      const result = generateFooter("Test Workflow", "https://github.com/test/repo/actions/runs/123", "", "", 42, 99, undefined);

      expect(result).toContain("for #42");
      expect(result).not.toContain("for #99");
    });

    it("should prioritize PR number over discussion number", () => {
      const result = generateFooter("Test Workflow", "https://github.com/test/repo/actions/runs/123", "", "", undefined, 99, 7);

      expect(result).toContain("for #99");
      expect(result).not.toContain("for discussion #7");
    });

    it("should include workflow installation instructions when source is provided", () => {
      const result = generateFooter("Test Workflow", "https://github.com/test/repo/actions/runs/123", "owner/repo/workflow.md@main", "https://github.com/owner/repo/blob/main/workflow.md", undefined, undefined, undefined);

      expect(result).toContain("gh aw add owner/repo/workflow.md@main");
      expect(result).toContain("See [usage guide](https://githubnext.github.io/gh-aw/guides/packaging-imports/)");
    });

    it("should not include installation instructions when source is empty", () => {
      const result = generateFooter("Test Workflow", "https://github.com/test/repo/actions/runs/123", "", "", undefined, undefined, undefined);

      expect(result).not.toContain("gh aw add");
    });

    it("should include both issue reference and installation instructions", () => {
      const result = generateFooter("Test Workflow", "https://github.com/test/repo/actions/runs/123", "owner/repo/workflow.md@main", "https://github.com/owner/repo/blob/main/workflow.md", 42, undefined, undefined);

      expect(result).toContain("for #42");
      expect(result).toContain("gh aw add owner/repo/workflow.md@main");
    });

    it("should start and end with newlines", () => {
      const result = generateFooter("Test Workflow", "https://github.com/test/repo/actions/runs/123", "", "", undefined, undefined, undefined);

      expect(result).toMatch(/^\n\n/);
      expect(result).toMatch(/\n$/);
    });

    it("should handle special characters in workflow name", () => {
      const result = generateFooter("Test Workflow (v2) [beta]", "https://github.com/test/repo/actions/runs/123", "", "", undefined, undefined, undefined);

      expect(result).toContain("> AI generated by [Test Workflow (v2) [beta]](https://github.com/test/repo/actions/runs/123)");
    });

    it("should include XML comment marker for traceability", () => {
      const result = generateFooter("Test Workflow", "https://github.com/test/repo/actions/runs/123", "", "", undefined, undefined, undefined);

      expect(result).toContain("<!-- gh-aw-agentic-workflow: Test Workflow");
      expect(result).toContain("run: https://github.com/test/repo/actions/runs/123 -->");
    });

    it("should include engine metadata in XML marker when env vars are set", async () => {
      // Set env vars before re-importing
      process.env.GH_AW_ENGINE_ID = "copilot";
      process.env.GH_AW_ENGINE_VERSION = "1.0.0";
      process.env.GH_AW_ENGINE_MODEL = "gpt-5";

      // Re-import to pick up new env vars
      vi.resetModules();
      const freshModule = await import("./generate_footer.cjs");

      const result = freshModule.generateFooter("Test Workflow", "https://github.com/test/repo/actions/runs/123", "", "", undefined, undefined, undefined);

      expect(result).toContain("<!-- gh-aw-agentic-workflow: Test Workflow");
      expect(result).toContain("engine: copilot");
      expect(result).toContain("version: 1.0.0");
      expect(result).toContain("model: gpt-5");
      expect(result).toContain("run: https://github.com/test/repo/actions/runs/123 -->");
    });
  });

  describe("generateXMLMarker", () => {
    it("should generate basic XML marker with workflow name and run URL", () => {
      const result = generateXMLMarker("Test Workflow", "https://github.com/test/repo/actions/runs/123");

      expect(result).toBe("<!-- gh-aw-agentic-workflow: Test Workflow, run: https://github.com/test/repo/actions/runs/123 -->");
    });

    it("should include engine ID when env var is set", async () => {
      process.env.GH_AW_ENGINE_ID = "copilot";

      vi.resetModules();
      const freshModule = await import("./generate_footer.cjs");

      const result = freshModule.generateXMLMarker("Test Workflow", "https://github.com/test/repo/actions/runs/123");

      expect(result).toBe("<!-- gh-aw-agentic-workflow: Test Workflow, engine: copilot, run: https://github.com/test/repo/actions/runs/123 -->");
    });

    it("should include engine version when env var is set", async () => {
      process.env.GH_AW_ENGINE_ID = "copilot";
      process.env.GH_AW_ENGINE_VERSION = "2.0.0";

      vi.resetModules();
      const freshModule = await import("./generate_footer.cjs");

      const result = freshModule.generateXMLMarker("Test Workflow", "https://github.com/test/repo/actions/runs/123");

      expect(result).toBe("<!-- gh-aw-agentic-workflow: Test Workflow, engine: copilot, version: 2.0.0, run: https://github.com/test/repo/actions/runs/123 -->");
    });

    it("should include all engine metadata when all env vars are set", async () => {
      process.env.GH_AW_ENGINE_ID = "copilot";
      process.env.GH_AW_ENGINE_VERSION = "1.0.0";
      process.env.GH_AW_ENGINE_MODEL = "gpt-5";

      vi.resetModules();
      const freshModule = await import("./generate_footer.cjs");

      const result = freshModule.generateXMLMarker("Test Workflow", "https://github.com/test/repo/actions/runs/123");

      expect(result).toBe("<!-- gh-aw-agentic-workflow: Test Workflow, engine: copilot, version: 1.0.0, model: gpt-5, run: https://github.com/test/repo/actions/runs/123 -->");
    });

    it("should handle special characters in workflow name", async () => {
      const result = generateXMLMarker("Test Workflow (v2) [beta]", "https://github.com/test/repo/actions/runs/123");

      expect(result).toContain("gh-aw-agentic-workflow: Test Workflow (v2) [beta]");
    });

    it("should include tracker-id when env var is set", async () => {
      process.env.GH_AW_TRACKER_ID = "my-tracker-12345";

      vi.resetModules();
      const freshModule = await import("./generate_footer.cjs");

      const result = freshModule.generateXMLMarker("Test Workflow", "https://github.com/test/repo/actions/runs/123");

      expect(result).toBe("<!-- gh-aw-agentic-workflow: Test Workflow, gh-aw-tracker-id: my-tracker-12345, run: https://github.com/test/repo/actions/runs/123 -->");
    });

    it("should include tracker-id with engine metadata when all env vars are set", async () => {
      process.env.GH_AW_ENGINE_ID = "copilot";
      process.env.GH_AW_ENGINE_VERSION = "1.0.0";
      process.env.GH_AW_ENGINE_MODEL = "gpt-5";
      process.env.GH_AW_TRACKER_ID = "workflow-2024-q1";

      vi.resetModules();
      const freshModule = await import("./generate_footer.cjs");

      const result = freshModule.generateXMLMarker("Test Workflow", "https://github.com/test/repo/actions/runs/123");

      expect(result).toBe("<!-- gh-aw-agentic-workflow: Test Workflow, gh-aw-tracker-id: workflow-2024-q1, engine: copilot, version: 1.0.0, model: gpt-5, run: https://github.com/test/repo/actions/runs/123 -->");
    });
  });
});
