#!/bin/bash
set -e

echo "[entrypoint] Agentic Workflow Firewall - Agent Container"
echo "[entrypoint] =================================="

# Fix DNS configuration - ensure external DNS works alongside Docker's embedded DNS
# Docker's embedded DNS (127.0.0.11) is used for service name resolution (e.g., squid-proxy)
# Trusted external DNS servers are used for internet domain resolution
echo "[entrypoint] Configuring DNS..."
if [ -f /etc/resolv.conf ]; then
  # Backup original resolv.conf
  cp /etc/resolv.conf /etc/resolv.conf.orig

  # Get DNS servers from environment (default to Google DNS)
  DNS_SERVERS="${AWF_DNS_SERVERS:-8.8.8.8,8.8.4.4}"

  # Create new resolv.conf with Docker embedded DNS first, then trusted external DNS servers
  {
    echo "# Generated by awf entrypoint"
    echo "# Docker embedded DNS for service name resolution (squid-proxy, etc.)"
    echo "nameserver 127.0.0.11"
    echo "# Trusted external DNS servers for internet domain resolution"

    # Add each trusted DNS server
    IFS=',' read -ra DNS_ARRAY <<< "$DNS_SERVERS"
    for dns_server in "${DNS_ARRAY[@]}"; do
      dns_server=$(echo "$dns_server" | tr -d ' ')
      if [ -n "$dns_server" ]; then
        echo "nameserver $dns_server"
      fi
    done

    echo "options ndots:0"
  } > /etc/resolv.conf

  echo "[entrypoint] DNS configured with Docker embedded DNS (127.0.0.11) and trusted servers: $DNS_SERVERS"
fi

# Setup Docker socket permissions if Docker socket is mounted
# This allows MCP servers that run as Docker containers to work
if [ -S /var/run/docker.sock ]; then
  echo "[entrypoint] Configuring Docker socket access..."
  # Get the GID of the docker socket
  DOCKER_GID=$(stat -c '%g' /var/run/docker.sock)
  # Create docker group with same GID as host's docker socket
  if ! getent group docker > /dev/null 2>&1; then
    groupadd -g "$DOCKER_GID" docker || true
  fi
  # Add root user to docker group
  usermod -aG docker root 2>/dev/null || true
  echo "[entrypoint] Docker socket configured (GID: $DOCKER_GID)"
fi

# Setup iptables rules
/usr/local/bin/setup-iptables.sh

# Print proxy environment
echo "[entrypoint] Proxy configuration:"
echo "[entrypoint]   HTTP_PROXY=$HTTP_PROXY"
echo "[entrypoint]   HTTPS_PROXY=$HTTPS_PROXY"

# Print network information
echo "[entrypoint] Network information:"
echo "[entrypoint]   IP address: $(hostname -I)"
echo "[entrypoint]   Hostname: $(hostname)"
echo "[entrypoint] =================================="
echo "[entrypoint] Executing command: $@"
echo ""

# Execute the provided command
exec "$@"
