#!/usr/bin/env node
/**
 * Generate GitHub Actions step summary from Squid firewall logs
 *
 * This script parses Squid proxy logs generated by awf and creates a markdown summary
 * showing firewall activity (allowed/blocked requests by domain).
 *
 * Usage:
 *   npx tsx scripts/ci/generate-firewall-summary.ts <logs-directory>
 *
 * The script reads access.log from the specified directory and writes a summary
 * to GITHUB_STEP_SUMMARY if available, or stdout otherwise.
 */

import * as fs from 'fs';
import * as path from 'path';
import { parseLogLine } from '../../src/logs/log-parser';
import { ParsedLogEntry } from '../../src/types';

/**
 * Analysis result for firewall logs
 */
interface FirewallAnalysis {
  totalRequests: number;
  allowedRequests: number;
  deniedRequests: number;
  allowedDomains: string[];
  deniedDomains: string[];
  requestsByDomain: Map<string, { allowed: number; denied: number }>;
}

/**
 * Analyzes parsed log entries to produce summary statistics
 */
function analyzeEntries(entries: ParsedLogEntry[]): FirewallAnalysis {
  const requestsByDomain = new Map<string, { allowed: number; denied: number }>();
  const allowedDomainsSet = new Set<string>();
  const deniedDomainsSet = new Set<string>();
  let allowedRequests = 0;
  let deniedRequests = 0;

  for (const entry of entries) {
    // Skip entries with no domain (shouldn't happen, but just in case)
    if (!entry.domain || entry.domain === '-') {
      continue;
    }

    // Get or create domain stats
    if (!requestsByDomain.has(entry.domain)) {
      requestsByDomain.set(entry.domain, { allowed: 0, denied: 0 });
    }
    const stats = requestsByDomain.get(entry.domain)!;

    if (entry.isAllowed) {
      stats.allowed++;
      allowedRequests++;
      allowedDomainsSet.add(entry.domain);
    } else {
      stats.denied++;
      deniedRequests++;
      deniedDomainsSet.add(entry.domain);
    }
  }

  return {
    totalRequests: entries.length,
    allowedRequests,
    deniedRequests,
    allowedDomains: Array.from(allowedDomainsSet).sort(),
    deniedDomains: Array.from(deniedDomainsSet).sort(),
    requestsByDomain,
  };
}

/**
 * Generates a markdown summary for GitHub Actions step summary
 */
function generateSummary(analysis: FirewallAnalysis): string {
  const {
    totalRequests,
    allowedRequests,
    deniedRequests,
    requestsByDomain,
  } = analysis;

  // Filter out invalid domains
  const validDomains = Array.from(requestsByDomain.keys())
    .filter(domain => domain !== '-' && domain !== '')
    .sort();

  const uniqueDomainCount = validDomains.length;

  let summary = '### 🔥 Firewall Activity\n\n';
  summary += '<details>\n';
  summary += `<summary>📊 ${totalRequests} request${totalRequests !== 1 ? 's' : ''} | `;
  summary += `${allowedRequests} allowed | `;
  summary += `${deniedRequests} blocked | `;
  summary += `${uniqueDomainCount} unique domain${uniqueDomainCount !== 1 ? 's' : ''}</summary>\n\n`;

  if (uniqueDomainCount > 0) {
    summary += '| Domain | Allowed | Denied |\n';
    summary += '|--------|---------|--------|\n';

    for (const domain of validDomains) {
      const stats = requestsByDomain.get(domain)!;
      summary += `| ${domain} | ${stats.allowed} | ${stats.denied} |\n`;
    }
  } else {
    summary += 'No firewall activity detected.\n';
  }

  summary += '\n</details>\n\n';
  return summary;
}

/**
 * Main function
 */
function main(): void {
  const args = process.argv.slice(2);

  if (args.length < 1) {
    console.error('Usage: generate-firewall-summary.ts <logs-directory>');
    console.error('');
    console.error('Example:');
    console.error('  npx tsx scripts/ci/generate-firewall-summary.ts /tmp/gh-aw/sandbox/firewall/logs/');
    process.exit(1);
  }

  const logsDir = args[0];

  // Check if directory exists
  if (!fs.existsSync(logsDir)) {
    console.log(`No firewall logs directory found at: ${logsDir}`);
    return;
  }

  // Find log files in the directory
  const files = fs.readdirSync(logsDir).filter(file => file.endsWith('.log'));

  if (files.length === 0) {
    console.log(`No firewall log files found in: ${logsDir}`);
    return;
  }

  console.log(`Found ${files.length} firewall log file(s)`);

  // Parse all log files
  const entries: ParsedLogEntry[] = [];

  for (const file of files) {
    const filePath = path.join(logsDir, file);
    console.log(`Parsing firewall log: ${file}`);

    const content = fs.readFileSync(filePath, 'utf8');
    const lines = content.split('\n').filter(line => line.trim());

    for (const line of lines) {
      const entry = parseLogLine(line);
      if (entry) {
        entries.push(entry);
      }
    }
  }

  // Analyze entries
  const analysis = analyzeEntries(entries);

  // Generate summary
  const summary = generateSummary(analysis);

  // Write to GITHUB_STEP_SUMMARY or stdout
  const summaryPath = process.env.GITHUB_STEP_SUMMARY;
  if (summaryPath) {
    fs.appendFileSync(summaryPath, summary);
    console.log('Firewall log summary generated successfully');
  } else {
    console.log('');
    console.log('--- Summary ---');
    console.log(summary);
  }
}

main();
