import { SquidConfig } from './types';

/**
 * Generates Squid proxy configuration with domain whitelisting
 */
export function generateSquidConfig(config: SquidConfig): string {
  const { domains, port } = config;

  // Generate ACL entries for allowed domains
  // Use dot-prefix for subdomain matching (e.g., .github.com matches both github.com and api.github.com)
  const normalizedDomains = domains.map(domain => {
    // Normalize domain - remove protocol if present
    return domain.replace(/^https?:\/\//, '').replace(/\/$/, '');
  });

  // Remove redundant subdomains (e.g., if github.com is present, api.github.com is redundant)
  const uniqueDomains = normalizedDomains.filter((domain, index, arr) => {
    // Check if this domain is a subdomain of another domain in the list
    return !arr.some((otherDomain, otherIndex) => {
      if (index === otherIndex) return false;
      // Check if domain is a subdomain of otherDomain (but not an exact duplicate)
      return domain !== otherDomain && domain.endsWith('.' + otherDomain);
    });
  });

  // If domains array is empty, don't generate domain ACLs (allow all domains)
  const domainAcls = uniqueDomains.length > 0
    ? uniqueDomains
        .map(domain => {
          // Add leading dot for subdomain matching unless already present
          const domainPattern = domain.startsWith('.') ? domain : `.${domain}`;
          return `acl allowed_domains dstdomain ${domainPattern}`;
        })
        .join('\n')
    : '# WARNING: No domain restrictions configured - all outbound traffic is allowed';

  // Construct access rules - conditionally include domain filtering
  const domainFilterRule = uniqueDomains.length > 0
    ? `
# Deny requests to unknown domains (not in allow-list)
# This applies to all sources including localnet
http_access deny !allowed_domains
`
    : `
# WARNING: No domain filtering configured - all outbound connections are allowed
`;

  return `# Squid configuration for egress traffic control
# Generated by awf

# Custom log format with detailed connection information
# Format: timestamp client_ip:port dest_domain dest_ip:port protocol method status decision url user_agent
# Note: For CONNECT requests (HTTPS), the domain is in the URL field
logformat firewall_detailed %ts.%03tu %>a:%>p %{Host}>h %<a:%<p %rv %rm %>Hs %Ss:%Sh %ru "%{User-Agent}>h"

# Access log and cache configuration
access_log /var/log/squid/access.log firewall_detailed
cache_log /var/log/squid/cache.log
cache deny all

# Port configuration
http_port ${port}

# ACL definitions for allowed domains
${domainAcls}

# Network ACLs
acl localnet src 10.0.0.0/8
acl localnet src 172.16.0.0/12
acl localnet src 192.168.0.0/16
acl localnet src fc00::/7
acl localnet src fe80::/10

# Port ACLs
acl SSL_ports port 443
acl Safe_ports port 80
acl Safe_ports port 443
acl CONNECT method CONNECT

# Access rules
# Deny unsafe ports first
http_access deny !Safe_ports
http_access deny CONNECT !SSL_ports
${domainFilterRule}
# Allow from trusted sources (after domain filtering)
http_access allow localnet
http_access allow localhost

# Deny everything else
http_access deny all

# Disable caching
cache deny all

# DNS settings
dns_nameservers 8.8.8.8 8.8.4.4

# Forwarded headers
forwarded_for delete
via off

# Error page customization
error_directory /usr/share/squid/errors/en

# Memory and file descriptor limits
cache_mem 64 MB
maximum_object_size 0 KB

# Timeout settings for streaming/long-lived connections (AI inference APIs)
# read_timeout: Time to wait for data from server before giving up
# Increased to accommodate long AI inference calls and SSE streaming
read_timeout 30 minutes

# connect_timeout: Time to wait for TCP connection to origin server
connect_timeout 30 seconds

# request_timeout: Time to wait for client to send first request after connection
request_timeout 2 minutes

# persistent_request_timeout: Time to wait for next request on persistent connection
persistent_request_timeout 2 minutes

# pconn_timeout: How long to keep idle persistent connections to servers
pconn_timeout 2 minutes

# client_lifetime: Maximum time a client connection can be open
# Set high to accommodate long streaming sessions
client_lifetime 8 hours

# half_closed_clients: Allow half-closed connections for streaming
# Critical for SSE where server sends but client doesn't respond
half_closed_clients on

# Debugging (can be enabled for troubleshooting)
# debug_options ALL,1 33,2
`;
}
