import { SquidConfig } from './types';

/**
 * Generates Squid proxy configuration with domain whitelisting
 */
export function generateSquidConfig(config: SquidConfig): string {
  const { domains, port } = config;

  // Generate ACL entries for allowed domains
  // Use dot-prefix for subdomain matching (e.g., .github.com matches both github.com and api.github.com)
  const domainAcls = domains
    .map(domain => {
      // Normalize domain - remove protocol if present
      const cleanDomain = domain.replace(/^https?:\/\//, '').replace(/\/$/, '');
      // Add leading dot for subdomain matching unless already present
      const domainPattern = cleanDomain.startsWith('.') ? cleanDomain : `.${cleanDomain}`;
      return `acl allowed_domains dstdomain ${domainPattern}`;
    })
    .join('\n');

  return `# Squid configuration for egress traffic control
# Generated by firewall-wrapper

# Access log and cache configuration
access_log /var/log/squid/access.log squid
cache_log /var/log/squid/cache.log
cache deny all

# Port configuration
http_port ${port}

# ACL definitions for allowed domains
${domainAcls}

# Network ACLs
acl localnet src 10.0.0.0/8
acl localnet src 172.16.0.0/12
acl localnet src 192.168.0.0/16
acl localnet src fc00::/7
acl localnet src fe80::/10

# Port ACLs
acl SSL_ports port 443
acl Safe_ports port 80
acl Safe_ports port 443
acl CONNECT method CONNECT

# Access rules
# Deny requests to unknown domains (not in allow-list)
http_access deny !allowed_domains
http_access deny !Safe_ports
http_access deny CONNECT !SSL_ports
http_access allow localnet
http_access allow localhost
http_access deny all

# Disable caching
cache deny all

# DNS settings
dns_nameservers 8.8.8.8 8.8.4.4

# Forwarded headers
forwarded_for delete
via off

# Error page customization
error_directory /usr/share/squid/errors/en

# Logging
logformat combined %>a %[ui %[un [%tl] "%rm %ru HTTP/%rv" %>Hs %<st "%{Referer}>h" "%{User-Agent}>h" %Ss:%Sh
access_log /var/log/squid/access.log combined

# Memory and file descriptor limits
cache_mem 64 MB
maximum_object_size 0 KB

# Debugging (can be enabled for troubleshooting)
# debug_options ALL,1 33,2
`;
}
