name: Test Domain Filtering with Curl

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-curl-filtering:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install
          npm run build

      - name: Make wrapper available globally with sudo
        run: |
          # Create sudo wrapper script for iptables manipulation
          sudo tee /usr/local/bin/awf > /dev/null <<EOF
          #!/bin/bash
          exec $(which node) $GITHUB_WORKSPACE/dist/cli.js "\$@"
          EOF
          sudo chmod +x /usr/local/bin/awf
          which awf
          awf --version

      - name: Run comprehensive domain filtering tests
        timeout-minutes: 10
        run: |
          set -e
          ./scripts/ci/test-curl-filtering.sh

      - name: Upload test logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: curl-filtering-test-logs
          path: /tmp/curl-test-*.log
          if-no-files-found: warn

      - name: Test Summary
        if: always()
        run: |
          echo "=========================================="
          echo "Domain Filtering Test Results"
          echo "=========================================="
          echo "This test validates:"
          echo "  ✓ Allowed domains are accessible via curl"
          echo "  ✓ Blocked domains are denied by Squid proxy"
          echo "  ✓ Firewall correctly applies ACL rules"
          echo "=========================================="
